<a href="https://colab.research.google.com/github/ekaratnida/Workshop/blob/main/de/Lab3/GetDataFromMongoDB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!python -m pip install "pymongo[srv]"==3.11

Collecting pymongo[srv]==3.11
  Downloading pymongo-3.11.0.tar.gz (771 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 771.7/771.7 kB 4.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Collecting dnspython<2.0.0,>=1.16.0 (from pymongo[srv]==3.11)
  Downloading dnspython-1.16.0-py2.py3-none-any.whl (188 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 188.4/188.4 kB 6.3 MB/s eta 0:00:00
Building wheels for collected packages: pymongo
  Building wheel for pymongo (setup.py) ... done
  Created wheel for pymongo: filename=pymongo-3.11.0-cp310-cp310-linux_x86_64.whl size=493667 sha256=1326b5f4f2f6acfd1e0429f297ed8857651e2236299c936807898072d65e1cf1
  Stored in directory: /root/.cache/pip/wheels/df/6e/99/27524029bf53fd025e0d44093d77e4fc0b27c6344acd6f3e86
Successfully built pymongo
Installing collected packages: pymongo, dnspython
Successfully installed dnspython-1.16.0 pymongo-3.11.0

In [ ]:
from pymongo.mongo_client import MongoClient

uri = "mongodb+srv://airflow1:1234@cluster0.5xrwr0a.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"

# Create a new client and connect to the server
client = MongoClient(uri)

# Send a ping to confirm a successful connection
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

Pinged your deployment. You successfully connected to MongoDB!

In [ ]:
try:
    client.admin.command('ping')
    print("Pinged your deployment. You successfully connected to MongoDB!")
except Exception as e:
    print(e)

In [ ]:
# database and collection code goes here
db = client.MyDB
coll = db.currency_collection
# find code goes here
cursor = coll.find()
# iterate code goes here
for doc in cursor:
    #print(doc)
    #print(doc['base'])
    #print(doc['rates']['2022-01-03'])
    pass

x = doc['rates']['2022-01-03']
print(x)

{'AUD': 1.5691, 'BGN': 1.9558, 'BRL': 6.3539, 'CAD': 1.442, 'CHF': 1.0372, 'CNY': 7.2174, 'CZK': 24.818, 'DKK': 7.4382, 'GBP': 0.84135, 'HKD': 8.8541, 'HRK': 7.519, 'HUF': 367.71, 'IDR': 16202, 'ILS': 3.5139, 'INR': 84.39, 'ISK': 147.6, 'JPY': 130.56, 'KRW': 1354.4, 'MXN': 23.226, 'MYR': 4.7379, 'NOK': 10.0013, 'NZD': 1.6651, 'PHP': 58.051, 'PLN': 4.5895, 'RON': 4.9483, 'RUB': 84.53, 'SEK': 10.2958, 'SGD': 1.5333, 'THB': 37.665, 'TRY': 15.0777, 'USD': 1.1355, 'ZAR': 17.9661}

### Reference: https://www.mongodb.com/docs/guides/crud/read/

In [ ]:
print(type(x))

<class 'dict'>

In [ ]:
import plotly.express as px
import pandas as pd
df = pd.DataFrame.from_dict(x, orient='index')
#df.reset_index(level=0, inplace=True)
df.head()
#df.shape

          0
AUD  1.5691
BGN  1.9558
BRL  6.3539
CAD  1.4420
CHF  1.0372

In [ ]:
from google.colab import data_table
data_table.DataTable(df, include_index=True, num_rows_per_page=10)

In [ ]:
fig = px.bar(df)
fig.show()